spring:
  datasource:
    url: 'jdbc:postgresql://host.docker.internal:5432/hapi'
    username: postgres
    password: mysecretpassword
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false